package com.driss.pokemon.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFFB80069)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFFFD9E3)
val md_theme_light_onPrimaryContainer = Color(0xFF3E001F)
val md_theme_light_secondary = Color(0xFF745660)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFFFD9E3)
val md_theme_light_onSecondaryContainer = Color(0xFF2A151D)
val md_theme_light_tertiary = Color(0xFF7D5636)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFFFDCC3)
val md_theme_light_onTertiaryContainer = Color(0xFF2F1500)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFFFBFF)
val md_theme_light_onBackground = Color(0xFF201A1C)
val md_theme_light_surface = Color(0xFFFFFBFF)
val md_theme_light_onSurface = Color(0xFF201A1C)
val md_theme_light_surfaceVariant = Color(0xFFF2DDE2)
val md_theme_light_onSurfaceVariant = Color(0xFF514347)
val md_theme_light_outline = Color(0xFF837377)
val md_theme_light_inverseOnSurface = Color(0xFFFAEEF0)
val md_theme_light_inverseSurface = Color(0xFF352F30)
val md_theme_light_inversePrimary = Color(0xFFFFB0CB)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFFB80069)
val md_theme_light_outlineVariant = Color(0xFFD5C2C6)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFFFFB0CB)
val md_theme_dark_onPrimary = Color(0xFF640036)
val md_theme_dark_primaryContainer = Color(0xFF8D004F)
val md_theme_dark_onPrimaryContainer = Color(0xFFFFD9E3)
val md_theme_dark_secondary = Color(0xFFE2BDC7)
val md_theme_dark_onSecondary = Color(0xFF422932)
val md_theme_dark_secondaryContainer = Color(0xFF5A3F48)
val md_theme_dark_onSecondaryContainer = Color(0xFFFFD9E3)
val md_theme_dark_tertiary = Color(0xFFF0BC95)
val md_theme_dark_onTertiary = Color(0xFF48290D)
val md_theme_dark_tertiaryContainer = Color(0xFF623F21)
val md_theme_dark_onTertiaryContainer = Color(0xFFFFDCC3)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF201A1C)
val md_theme_dark_onBackground = Color(0xFFEBE0E1)
val md_theme_dark_surface = Color(0xFF201A1C)
val md_theme_dark_onSurface = Color(0xFFEBE0E1)
val md_theme_dark_surfaceVariant = Color(0xFF514347)
val md_theme_dark_onSurfaceVariant = Color(0xFFD5C2C6)
val md_theme_dark_outline = Color(0xFF9E8C91)
val md_theme_dark_inverseOnSurface = Color(0xFF201A1C)
val md_theme_dark_inverseSurface = Color(0xFFEBE0E1)
val md_theme_dark_inversePrimary = Color(0xFFB80069)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFFFFB0CB)
val md_theme_dark_outlineVariant = Color(0xFF514347)
val md_theme_dark_scrim = Color(0xFF000000)


val seed = Color(0xFFFF2796)
val Fire = Color(0xFFF57F17)
val light_Fire = Color(0xFF964900)
val light_onFire = Color(0xFFFFFFFF)
val light_FireContainer = Color(0xFFFFDCC7)
val light_onFireContainer = Color(0xFF311300)
val dark_Fire = Color(0xFFFFB787)
val dark_onFire = Color(0xFF502400)
val dark_FireContainer = Color(0xFF723600)
val dark_onFireContainer = Color(0xFFFFDCC7)

val semi_transparent_white = Color.White.copy(alpha = 0.7f)
